// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uawzpjdgxijbdevdngow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhd3pwamRneGlqYmRldmRuZ293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjAzMzIsImV4cCI6MjA2NjIzNjMzMn0.BySj5szhfSFGli8eAC8fbAqYppeCRBBImy2fVjvZ1-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);